config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :groups
    end
  end

  resources :groups do
    member do
      post :join
    end
  end

  resources :events do
    member do
      post :attend
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :events
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      current_user.join_group(@group.id)
      flash[:success] = "Group created."
      redirect_to @group
    else
      flash.now[:error] = "Something went wrong."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def join
    group = Group.find(params[:id])
    current_user.join_group(group.id)
    redirect_to group
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_past_events.html.erb
<div class="row">
  <div class="col">
    <%= content_tag :p, "Something about past events" %>
  </div>
</div>

app/views/groups/_upcoming_events.html.erb
<div class="row">
  <div class="col">
    <%= content_tag :p, "Something about upcoming events" %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <h3>Groups</h3>

  <div class="row">
    <% @groups.each do |group| %>
      <div class="card" style="width: 18rem;">
        <!-- <img class="card-img-top" src=".../100px180/" alt="Card image cap"> -->
        <div class="card-body">
          <h5 class="card-title"><%= group.name %></h5>
          <p class="card-text"><%= group.description %></p>
          <%= link_to group.name, group_path(group), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col">
    <%= content_tag :h3, "Create new group" %>
    <%= simple_form_for @group do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.submit "Create Group", class: "btn btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="jumbotron">
        <h1 class="display-4"></h1>
        <%= content_tag :p, "#{@group.name} group banner, generic default picture (options to be provided), or even group movie" %>
        <hr class="my-4">
        <%= content_tag :p, "Some information about the #{@group.name}" %>
        <% unless current_user.group_member?(@group.id) %>
          <%= link_to "Join Group", join_group_path(@group.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Members" %>
          <ul>
            <% @group.members.each do |member| %>
              <%= link_to "<li>#{member.username}</li>".html_safe, user_path(member) %>
            <% end %>
            <% 5.times do %>
              <li>A member</li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Some info about the group (recent events, etc.)" %>
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <%= link_to "Upcoming Events", "#", class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Past Events", "#", class: "nav-link" %>
            </li>
          </ul>
          <!-- need to handle tabs -->
          <%= render 'upcoming_events' %>
          <%= render 'past_events' %>
        </div>
      </div>
    </div>
  </div>
</div>