config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :groups
    end
  end

  resources :groups do
    member do
      post :join
    end
  end

  resources :events do
    member do
      post :attend
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :omniauthable,
         :confirmable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :lockable

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :reservations
  has_many :events, through: :reservations

  validates_presence_of :username
  validates :image, file_size: { less_than: 1.megabytes }

  def join_group(group_id, role={})
    self.memberships.create(group_id: group_id)
    # need to add logic for becoming group admin or other roles
    # need to add logic for admin approval
  end

  def group_member?(group_id)
    groups.pluck(:id).include?(group_id)
  end

  def attend_event(event_id, role={})
    self.reservations.create(event_id: event_id)
    # need to add logic for becoming event admin or other roles
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your profile has been updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def groups
    @groups = User.find(params[:id]).groups
  end

  private

    def user_params
      params.require(:user).permit(:about_me, :image, :image_cache)
    end
end

app/views/users/_group.html.erb
<% @groups.each do |group| %>
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <%= content_tag :h5, "#{group.name}" %>
        <%= content_tag :p, "#{group.description}" %>
        <%= link_to "#{group.name}'s Page", group, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= content_tag :h3, "Edit info for #{@user.username}!" %>
      <%= simple_form_for(@user) do |f| %>
        <!-- temporary - probably will want to update this -->
        <%= f.input :image, label: "Profile Image" %>
        <%= image_tag(@user.image.profile_thumb.url) if @user.image? %>
        <%= f.input :image_cache, as: :hidden %>
        <%= f.input :about_me %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/groups.html.erb
<div class="row">
  <%= render 'group' %>
</div>

app/views/users/show.html.erb
<!-- need to show personal home page if current user is the same as the user -->
<div class="container">
  <div class="row">
    <div class="col">
      <div class="jumbotron">
        <div class="row">
          <div class="col-5 text-center">
            <%= image_tag(@user.image.profile_thumb.url) if @user.image? %>
          </div>
          <div class="col">
            <h1 class="display-4"></h1>
            <%= content_tag :p, "Temporary User page title for #{@user.username}!" %>
            <hr class="my-4">
            <%= content_tag :p, "#{@user.about_me}" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "#{@user.username}'s recent activity, upcoming events, stats, and other stuff" %>
          <%= content_tag :p, "#{@user.username} is so cool!", class: "card-text" %>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Groups" %>
          <ul>
            <% @user.groups.each do |group| %>
              <%= link_to "<li>#{group.name}</li>".html_safe, group_path(group.id) %>
            <% end %>
          </ul>
          <!-- need to fix the username later -->
          <%= link_to "See #{@user.username}'s/your groups", groups_user_path(@user.id), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>