config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :groups
    end
  end

  resources :groups do
    member do
      post :join
    end
  end

  resources :events do
    member do
      post :attend
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group # later make the user its own group
  has_many :reservations, dependent: :destroy
  has_many :attendees, through: :reservations, source: :user

  validates_presence_of :start_datetime

  def same_day_event?
    return false if end_datetime.blank?
    start_datetime.to_date == end_datetime.to_date
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @groups = current_user.groups # fix this to show just user's admin authorized groups
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      current_user.attend_event(@event.id)
      # need to add logic to add user as admin
      flash[:success] = "Event created."
      redirect_to @event
    else
      flash.now[:error] = "Something went wrong."
      render :new
    end
  end

  def attend
    event = Event.find(params[:id])
    current_user.attend_event(params[:id])
    redirect_to event
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :group_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def display_event_datetime(event)
    start_datetime = event.start_datetime
    end_datetime = event.end_datetime
    if end_datetime
      if event.same_day_event?
        # "Tuesday, October 5, 2017 at 3:20 PM - 5:20 PM"
        full_date_and_time(start_datetime) + " - " + time_only(end_datetime)
      else
        # "Oct 5, 2017 at 3:20 PM - Oct 6, 2017 at 5:20 PM"
        abbrv_full_date_and_time(start_datetime) + " - " + abbrv_full_date_and_time(end_datetime)
      end
    else
      full_date_and_time(start_datetime)
    end
  end

  private

    def full_date_and_time(datetime)
      # Monday, January 1, 2018 at 1:55 PM
      datetime.strftime("%A, %B %-d, %Y at %l:%M %p")
    end

    def abbrv_full_date_and_time(datetime)
      # Oct 5, 2017 at 3:20 PM
      datetime.strftime("%b %-d, %Y at %l:%M %p")
    end

    def time_only(datetime)
      # 1:55 PM
      datetime.strftime("%l:%M %p")
    end
end

app/views/events/index.html.erb
<div class="container">
  <h3>Events</h3>

  <div class="row">
    <% @events.each do |event| %>
      <div class="card" style="width: 18rem;">
        <!-- <img class="card-img-top" src=".../100px180/" alt="Card image cap"> -->
        <div class="card-body">
          <h5 class="card-title"><%= event.name %></h5>
          <p class="card-text"><%= event.description %></p>
          <%= link_to event.name, event_path(event), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col">
    <%= content_tag :h3, "Create new event" %>
    <%= simple_form_for @event do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :group_id, collection: @groups %>
      <%= f.input :start_datetime, as: :string, :input_html => { :id => "datetimepicker1" } %>
      <%= f.input :end_datetime, as: :string, :input_html => { :id => "datetimepicker2" } %>
      <%= f.submit "Create Event", class: "btn btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row" style="background-color:lightyellow;">
    <div class="col" style="padding:10px;">
      <div class="jumbotron">
        <h1 class="display-4"></h1>
        <div class="row">
          <div class="col">
            <%= content_tag :p, "#{@event.name}", class: "lead" %>
          </div>
          <div class="col">
            <!-- owners (admins too?) can create a template out of existing event -->
            <button type="button" class="btn btn-secondary float-right">Create template</button>
          </div>
        </div>
        <hr class="my-4">
        <div class="row">
          <div class="col">
            <%= content_tag :p, "#{@event.description}" %>
            <%= content_tag :p do %>
              Hosted by <%= link_to @event.group.name, group_path(@event.group) %>
            <% end %>
          </div>
          <div class="col">
            <i class="fa fa-calendar"></i>&nbsp;<%= display_event_datetime(@event) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="background-color:lightblue;">
    <div class="col-7" style="padding:10px;">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Details" %>
          <%= content_tag :p, "Here it will show details about the event", class: "card-text" %>
          <%= link_to "See more", "#", class: "card-link" %>
        </div>
      </div>
    </div>
    <div class="col" style="padding:10px;">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Attendees" %>
          <ul>
            <% @event.attendees.each do |attendee| %>
              <%= link_to "<li>#{attendee.username}</li>".html_safe, user_path(attendee) %>
            <% end %>
          </ul>
          <%= link_to "See more", "#", class: "card-link" %>
          <div class="row">
            <div class="col">
              <%= link_to "Join", attend_event_path(@event.id), method: :post, class: "btn btn-light" %>
            </div>
            <div class="col">
              <%= link_to "Maybe", "#", class: "btn btn-light" %>
            </div>
            <div class="col">
              <%= link_to "Cannot join", "#", class: "btn btn-light" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="background-color:lightblue">
    <div class="col" style="padding:10px;">
      <div class="card">
        <div class="card-body">
          <%= content_tag :h5, "Comments" %>
          <%= content_tag :p, "Here it will show comments", class: "card-text" %>
          <%= link_to "See more", "#", class: "card-link" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row" style="background-color:lightgreen;">
    <div class="col" style="padding:10px;">
      <img class="img-fluid" src="http://fjaerestad.no/wp-content/uploads/2015/04/geolocation_and_google_maps.jpg">
    </div>
  </div>
</div>