config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :groups
    end
  end

  resources :groups do
    member do
      post :join
    end
  end

  resources :events do
    member do
      post :attend
    end
  end
end

app/views/layouts/_head.html.erb
<head>
  <title>OpenRec</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "OpenRec", root_path, id: 'open_rec_logo' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <div class="btn-group ml-auto">
          <%= button_tag "Create", {
            class: "btn btn-success dropdown-toggle",
            type: "button",
            id: "createDropdown",
            data: { toggle: "dropdown" },
            aria: { haspopup: true, expanded: false }
            } %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="createDropdown">
            <%= link_to "Events", new_event_path, class: "dropdown-item" %>
            <%= link_to "Groups", new_group_path, class: "dropdown-item" %>
          </div>
        </div>
        <div class="btn-group">
          <%= button_tag current_user.username, {
            class: "btn btn-secondary dropdown-toggle",
            type: "button",
            id: "userDropdown",
            data: { toggle: "dropdown" },
            aria: { haspopup: true, expanded: false }
            } %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <h6 class="dropdown-header">About You</h6>
            <%= link_to "Your Page", current_user, class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Settings</h6>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item", class: "dropdown-item" %>
            <%= link_to "General Settings", "#", class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, {
              method: :delete,
              class: "dropdown-item" } %>
          </div>
        </div>
      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Login", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="<%= flash_messages(message_type) %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>